export const GET_TASKS = 'GET_TASKS';
export const SET_TASKS = 'SET_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const UPLOAD_FILES = 'UPLOAD_FILES';
export const SORTED_TASKS = 'SORTED_TASKS';
export const CHANGE_STATUS_DEVELOPMENT = 'CHANGE_STATUS_DEVELOPMENT';